# Generated by Django 4.2 on 2023-06-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeritaKlasifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, db_column='judul', max_length=200, null=True)),
                ('link', models.CharField(blank=True, db_column='link', max_length=500, null=True)),
                ('tanggal', models.DateField(blank=True, db_column='tanggal', null=True)),
                ('isi_berita', models.TextField(blank=True, db_column='isi_berita', null=True)),
                ('sumber', models.CharField(blank=True, db_column='sumber', max_length=255, null=True)),
                ('kemiskinan', models.IntegerField(blank=True, db_column='kemiskinan', null=True)),
                ('pengangguran', models.IntegerField(blank=True, db_column='pengangguran', null=True)),
                ('demokrasi', models.IntegerField(blank=True, db_column='demokrasi', null=True)),
                ('inflasi', models.IntegerField(blank=True, db_column='inflasi', null=True)),
                ('pertumbuhan_ekonomi', models.IntegerField(blank=True, db_column='pertumbuhan_ekonomi', null=True)),
            ],
            options={
                'db_table': 'tes2',
                'managed': False,
            },
        ),
    ]
