# Generated by Django 4.2 on 2023-06-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_beritaklasifikasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demokrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
            ],
            options={
                'db_table': 'demokrasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inflasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
            ],
            options={
                'db_table': 'inflasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kemiskinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
            ],
            options={
                'db_table': 'kemiskinan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pengangguran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
            ],
            options={
                'db_table': 'pengangguran',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pertumbuhan_Ekonomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
            ],
            options={
                'db_table': 'pertumbuhan_ekonomi',
                'managed': False,
            },
        ),
    ]
