# Generated by Django 4.2.2 on 2023-06-18 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, db_column='judul', max_length=200, null=True)),
                ('link', models.CharField(blank=True, db_column='link', max_length=500, null=True)),
                ('tanggal', models.DateField(blank=True, db_column='tanggal', null=True)),
                ('isi_berita', models.TextField(blank=True, db_column='isi_berita', null=True)),
                ('sumber', models.CharField(blank=True, db_column='sumber', max_length=255, null=True)),
                ('kemiskinan', models.IntegerField(blank=True, db_column='kemiskinan', null=True)),
                ('pengangguran', models.IntegerField(blank=True, db_column='pengangguran', null=True)),
                ('demokrasi', models.IntegerField(blank=True, db_column='demokrasi', null=True)),
                ('inflasi', models.IntegerField(blank=True, db_column='inflasi', null=True)),
                ('pertumbuhan_ekonomi', models.IntegerField(blank=True, db_column='pertumbuhan_ekonomi', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pertumbuhan_Ekonomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
                ('berita', models.OneToOneField(db_column='berita_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='klasifikasi_berita.berita')),
            ],
        ),
        migrations.CreateModel(
            name='Pengangguran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
                ('berita', models.OneToOneField(db_column='berita_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='klasifikasi_berita.berita')),
            ],
        ),
        migrations.CreateModel(
            name='Kemiskinan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
                ('berita', models.OneToOneField(db_column='berita_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='klasifikasi_berita.berita')),
            ],
        ),
        migrations.CreateModel(
            name='Inflasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
                ('berita', models.OneToOneField(db_column='berita_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='klasifikasi_berita.berita')),
            ],
        ),
        migrations.CreateModel(
            name='Demokrasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naik', models.IntegerField(blank=True, db_column='naik', null=True)),
                ('turun', models.IntegerField(blank=True, db_column='turun', null=True)),
                ('tidak_ada', models.IntegerField(blank=True, db_column='tidak_ada', null=True)),
                ('berita', models.OneToOneField(db_column='berita_id', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='klasifikasi_berita.berita')),
            ],
        ),
    ]
