# Generated by Django 4.2 on 2023-06-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(blank=True, db_column='judul', max_length=200, null=True)),
                ('link', models.CharField(blank=True, db_column='link', max_length=500, null=True)),
                ('topik', models.CharField(blank=True, db_column='topik', max_length=255, null=True)),
                ('tanggal', models.DateField(blank=True, db_column='tanggal', null=True)),
                ('isi_berita', models.TextField(blank=True, db_column='isi_berita', null=True)),
                ('sumber', models.CharField(blank=True, db_column='sumber', max_length=255, null=True)),
            ],
            options={
                'db_table': 'berita',
                'managed': False,
            },
        ),
    ]
