# Generated by Django 4.2.2 on 2023-06-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klasifikasi_berita', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='status',
            field=models.CharField(blank=True, db_column='status', max_length=30, null=True),
        ),
    ]
